controller_list:
  - name: fake_mr_controller
    joints:
      - mr_track_rail
      - mr_joint_1
      - mr_joint_2
      - mr_joint_3
      - mr_joint_4
      - mr_joint_5
      - mr_joint_6
  - name: fake_wr_controller
    joints:
      - wr_track_rail
      - wr_joint_1
      - wr_joint_2
      - wr_joint_3
      - wr_joint_4
      - wr_joint_5
      - wr_joint_6
  - name: fake_all_controller
    joints:
      - wr_track_rail
      - wr_joint_1
      - wr_joint_2
      - wr_joint_3
      - wr_joint_4
      - wr_joint_5
      - wr_joint_6
      - mr_track_rail
      - mr_joint_1
      - mr_joint_2
      - mr_joint_3
      - mr_joint_4
      - mr_joint_5
      - mr_joint_6