# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  mr_joint_1:
    has_velocity_limits: true
    max_velocity: 3.054
    has_acceleration_limits: false
    max_acceleration: 0
  mr_joint_2:
    has_velocity_limits: true
    max_velocity: 3.054
    has_acceleration_limits: false
    max_acceleration: 0
  mr_joint_3:
    has_velocity_limits: true
    max_velocity: 3.054
    has_acceleration_limits: false
    max_acceleration: 0
  mr_joint_4:
    has_velocity_limits: true
    max_velocity: 4.363
    has_acceleration_limits: false
    max_acceleration: 0
  mr_joint_5:
    has_velocity_limits: true
    max_velocity: 4.363
    has_acceleration_limits: false
    max_acceleration: 0
  mr_joint_6:
    has_velocity_limits: true
    max_velocity: 6.283
    has_acceleration_limits: false
    max_acceleration: 0
  mr_track_rail:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  wr_joint_1:
    has_velocity_limits: true
    max_velocity: 3.054
    has_acceleration_limits: false
    max_acceleration: 0
  wr_joint_2:
    has_velocity_limits: true
    max_velocity: 3.054
    has_acceleration_limits: false
    max_acceleration: 0
  wr_joint_3:
    has_velocity_limits: true
    max_velocity: 3.054
    has_acceleration_limits: false
    max_acceleration: 0
  wr_joint_4:
    has_velocity_limits: true
    max_velocity: 4.363
    has_acceleration_limits: false
    max_acceleration: 0
  wr_joint_5:
    has_velocity_limits: true
    max_velocity: 4.363
    has_acceleration_limits: false
    max_acceleration: 0
  wr_joint_6:
    has_velocity_limits: true
    max_velocity: 6.283
    has_acceleration_limits: false
    max_acceleration: 0
  wr_track_rail:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0